// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DART_CLOSE_WEBVIEW`, `DART_CREATE_WEBVIEW`, `DART_GET_COOKIES`, `DART_OPEN_WEBVIEW`, `HostWebview`, `Webview`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`, `initialize`, `trace`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `close`, `close`, `create`, `create`, `get_cookies`, `get_cookies`, `open`, `open`, `poll_url_change_event`

Future<void> initializeWebviewCallbacks(
        {required FutureOr<Object> Function(String, BroadcastSenderString)
            createWebview,
        required FutureOr<void> Function(Object) openWebview,
        required FutureOr<void> Function(Object) closeWebview,
        required FutureOr<String> Function(Object, String) getCookies}) =>
    RustLib.instance.api.crateApiHostApiWebviewInitializeWebviewCallbacks(
        createWebview: createWebview,
        openWebview: openWebview,
        closeWebview: closeWebview,
        getCookies: getCookies);

Future<void> sendWebviewEvents(
        {required BroadcastSenderString tx, required String event}) =>
    RustLib.instance.api
        .crateApiHostApiWebviewSendWebviewEvents(tx: tx, event: event);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BroadcastSender < String >>>
abstract class BroadcastSenderString implements RustOpaqueInterface {}
