// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models/core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'senders.dart';

// These functions are ignored because they are not marked as `pub`: `js_executor_thread`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `create_context`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OpaqueSender>>
abstract class OpaqueSender implements RustOpaqueInterface {
  SenderPluginCommand get sender;

  set sender(SenderPluginCommand sender);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sender < PluginCommand >>>
abstract class SenderPluginCommand implements RustOpaqueInterface {}

class SpotubePlugin {
  final PluginArtistSender artist;
  final PluginAlbumSender album;
  final PluginAudioSourceSender audioSource;
  final PluginAuthSender auth;
  final PluginBrowseSender browse;
  final PluginCoreSender core;
  final PluginPlaylistSender playlist;
  final PluginSearchSender search;
  final PluginTrackSender track;
  final PluginUserSender user;

  const SpotubePlugin.raw({
    required this.artist,
    required this.album,
    required this.audioSource,
    required this.auth,
    required this.browse,
    required this.core,
    required this.playlist,
    required this.search,
    required this.track,
    required this.user,
  });

  Future<void> dispose({required OpaqueSender tx}) => RustLib.instance.api
      .crateApiPluginPluginSpotubePluginDispose(that: this, tx: tx);

  factory SpotubePlugin() =>
      RustLib.instance.api.crateApiPluginPluginSpotubePluginNew();

  static OpaqueSender newContext(
          {required String pluginScript,
          required PluginConfiguration pluginConfig}) =>
      RustLib.instance.api.crateApiPluginPluginSpotubePluginNewContext(
          pluginScript: pluginScript, pluginConfig: pluginConfig);

  @override
  int get hashCode =>
      artist.hashCode ^
      album.hashCode ^
      audioSource.hashCode ^
      auth.hashCode ^
      browse.hashCode ^
      core.hashCode ^
      playlist.hashCode ^
      search.hashCode ^
      track.hashCode ^
      user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpotubePlugin &&
          runtimeType == other.runtimeType &&
          artist == other.artist &&
          album == other.album &&
          audioSource == other.audioSource &&
          auth == other.auth &&
          browse == other.browse &&
          core == other.core &&
          playlist == other.playlist &&
          search == other.search &&
          track == other.track &&
          user == other.user;
}
