// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'models/auth.dart';
import 'models/core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'senders.dart';

// These functions are ignored because they are not marked as `pub`: `create_context`, `js_executor_thread`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `open_webview`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OpaqueSender>>
abstract class OpaqueSender implements RustOpaqueInterface {
  SenderPluginCommand get sender;

  set sender(SenderPluginCommand sender);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpotubePlugin>>
abstract class SpotubePlugin implements RustOpaqueInterface {
  Stream<AuthEventObject> authState();

  PluginAlbumSender get album;

  PluginArtistSender get artist;

  PluginAudioSourceSender get audioSource;

  PluginAuthSender get auth;

  PluginBrowseSender get browse;

  PluginCoreSender get core;

  PluginPlaylistSender get playlist;

  PluginSearchSender get search;

  PluginTrackSender get track;

  PluginUserSender get user;

  set album(PluginAlbumSender album);

  set artist(PluginArtistSender artist);

  set audioSource(PluginAudioSourceSender audioSource);

  set auth(PluginAuthSender auth);

  set browse(PluginBrowseSender browse);

  set core(PluginCoreSender core);

  set playlist(PluginPlaylistSender playlist);

  set search(PluginSearchSender search);

  set track(PluginTrackSender track);

  set user(PluginUserSender user);

  Future<void> close({required OpaqueSender tx});

  OpaqueSender createContext(
      {required String pluginScript,
      required PluginConfiguration pluginConfig});

  factory SpotubePlugin() =>
      RustLib.instance.api.crateApiPluginPluginSpotubePluginNew();
}
