// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'artist.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'album.freezed.dart';
part 'album.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

enum SpotubeAlbumType {
  album,
  single,
  compilation,
  ;
}

@freezed
sealed class SpotubeFullAlbumObject with _$SpotubeFullAlbumObject {
  const factory SpotubeFullAlbumObject({
    required String typeName,
    required String id,
    required String name,
    required List<SpotubeSimpleArtistObject> artists,
    required List<SpotubeImageObject> images,
    required String releaseDate,
    required String externalUri,
    required int totalTracks,
    required SpotubeAlbumType albumType,
    String? recordLabel,
    List<String>? genres,
  }) = _SpotubeFullAlbumObject;

  factory SpotubeFullAlbumObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeFullAlbumObjectFromJson(json);
}

@freezed
sealed class SpotubeSimpleAlbumObject with _$SpotubeSimpleAlbumObject {
  const factory SpotubeSimpleAlbumObject({
    required String typeName,
    required String id,
    required String name,
    required String externalUri,
    required List<SpotubeSimpleArtistObject> artists,
    required List<SpotubeImageObject> images,
    required SpotubeAlbumType albumType,
    String? releaseDate,
  }) = _SpotubeSimpleAlbumObject;

  factory SpotubeSimpleAlbumObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeSimpleAlbumObjectFromJson(json);
}
