// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'artist.freezed.dart';
part 'artist.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
sealed class SpotubeFullArtistObject with _$SpotubeFullArtistObject {
  const factory SpotubeFullArtistObject({
    required String id,
    required String name,
    required String externalUri,
    required List<SpotubeImageObject> images,
    List<String>? genres,
    int? followers,
  }) = _SpotubeFullArtistObject;

  factory SpotubeFullArtistObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeFullArtistObjectFromJson(json);
}

@freezed
sealed class SpotubeSimpleArtistObject with _$SpotubeSimpleArtistObject {
  const factory SpotubeSimpleArtistObject({
    required String id,
    required String name,
    required String externalUri,
    List<SpotubeImageObject>? images,
  }) = _SpotubeSimpleArtistObject;

  factory SpotubeSimpleArtistObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeSimpleArtistObjectFromJson(json);
}
