// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'audio_source.freezed.dart';
part 'audio_source.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class SpotubeAudioLosslessContainerQuality
    with _$SpotubeAudioLosslessContainerQuality {
  const SpotubeAudioLosslessContainerQuality._();
  const factory SpotubeAudioLosslessContainerQuality({
    required int bitDepth,
    required int sampleRate,
  }) = _SpotubeAudioLosslessContainerQuality;
  String toStringFmt() => RustLib.instance.api
          .crateApiPluginModelsAudioSourceSpotubeAudioLosslessContainerQualityToStringFmt(
        that: this,
      );

  factory SpotubeAudioLosslessContainerQuality.fromJson(
          Map<String, dynamic> json) =>
      _$SpotubeAudioLosslessContainerQualityFromJson(json);
}

@freezed
sealed class SpotubeAudioLossyContainerQuality
    with _$SpotubeAudioLossyContainerQuality {
  const SpotubeAudioLossyContainerQuality._();
  const factory SpotubeAudioLossyContainerQuality({
    required int bitrate,
  }) = _SpotubeAudioLossyContainerQuality;
  Future<String> toStringFmt() => RustLib.instance.api
          .crateApiPluginModelsAudioSourceSpotubeAudioLossyContainerQualityToStringFmt(
        that: this,
      );

  factory SpotubeAudioLossyContainerQuality.fromJson(
          Map<String, dynamic> json) =>
      _$SpotubeAudioLossyContainerQualityFromJson(json);
}

@freezed
sealed class SpotubeAudioSourceContainerPreset
    with _$SpotubeAudioSourceContainerPreset {
  const SpotubeAudioSourceContainerPreset._();

  const factory SpotubeAudioSourceContainerPreset.lossy({
    required SpotubeMediaCompressionType compressionType,
    required String name,
    required List<SpotubeAudioLossyContainerQuality> qualities,
  }) = SpotubeAudioSourceContainerPreset_Lossy;
  const factory SpotubeAudioSourceContainerPreset.lossless({
    required SpotubeMediaCompressionType compressionType,
    required String name,
    required List<SpotubeAudioLosslessContainerQuality> qualities,
  }) = SpotubeAudioSourceContainerPreset_Lossless;

  factory SpotubeAudioSourceContainerPreset.fromJson(
          Map<String, dynamic> json) =>
      _$SpotubeAudioSourceContainerPresetFromJson(json);

  String fileExtension() => RustLib.instance.api
          .crateApiPluginModelsAudioSourceSpotubeAudioSourceContainerPresetFileExtension(
        that: this,
      );
}

@freezed
sealed class SpotubeAudioSourceMatchObject
    with _$SpotubeAudioSourceMatchObject {
  const factory SpotubeAudioSourceMatchObject({
    required String id,
    required String title,
    required List<String> artists,
    required int duration,
    String? thumbnail,
    required String externalUri,
  }) = _SpotubeAudioSourceMatchObject;

  factory SpotubeAudioSourceMatchObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeAudioSourceMatchObjectFromJson(json);
}

@freezed
sealed class SpotubeAudioSourceStreamObject
    with _$SpotubeAudioSourceStreamObject {
  const factory SpotubeAudioSourceStreamObject({
    required String typeName,
    required String url,
    required String container,
    required SpotubeMediaCompressionType compressionType,
    String? codec,
    double? bitrate,
    int? bitDepth,
    double? sampleRate,
  }) = _SpotubeAudioSourceStreamObject;

  factory SpotubeAudioSourceStreamObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeAudioSourceStreamObjectFromJson(json);
}

enum SpotubeMediaCompressionType {
  lossy,
  lossless,
  ;
}
