// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `fmt`, `partial_cmp`

class AuthEventObject {
  final AuthEventType eventType;

  const AuthEventObject({
    required this.eventType,
  });

  @override
  int get hashCode => eventType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthEventObject &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType;
}

enum AuthEventType {
  login,
  refreshSession,
  logout,
  ;
}
