// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'playlist.dart';
import 'track.dart';
import 'user.dart';
part 'browse.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
sealed class SpotubeBrowseSectionObject with _$SpotubeBrowseSectionObject {
  const factory SpotubeBrowseSectionObject({
    required String id,
    required String title,
    required String externalUri,
    required bool browseMore,
    required List<SpotubeBrowseSectionResponseObjectItem> items,
  }) = _SpotubeBrowseSectionObject;
}

@freezed
sealed class SpotubeBrowseSectionResponseObjectItem
    with _$SpotubeBrowseSectionResponseObjectItem {
  const SpotubeBrowseSectionResponseObjectItem._();

  const factory SpotubeBrowseSectionResponseObjectItem.track(
    SpotubeFullTrackObject field0,
  ) = SpotubeBrowseSectionResponseObjectItem_Track;
  const factory SpotubeBrowseSectionResponseObjectItem.playlistFull(
    SpotubeFullPlaylistObject field0,
  ) = SpotubeBrowseSectionResponseObjectItem_PlaylistFull;
  const factory SpotubeBrowseSectionResponseObjectItem.playlistSimple(
    SpotubeSimplePlaylistObject field0,
  ) = SpotubeBrowseSectionResponseObjectItem_PlaylistSimple;
  const factory SpotubeBrowseSectionResponseObjectItem.albumSimple(
    SpotubeSimpleAlbumObject field0,
  ) = SpotubeBrowseSectionResponseObjectItem_AlbumSimple;
  const factory SpotubeBrowseSectionResponseObjectItem.albumFull(
    SpotubeFullAlbumObject field0,
  ) = SpotubeBrowseSectionResponseObjectItem_AlbumFull;
  const factory SpotubeBrowseSectionResponseObjectItem.artistFull(
    SpotubeFullArtistObject field0,
  ) = SpotubeBrowseSectionResponseObjectItem_ArtistFull;
  const factory SpotubeBrowseSectionResponseObjectItem.artistSimple(
    SpotubeSimpleArtistObject field0,
  ) = SpotubeBrowseSectionResponseObjectItem_ArtistSimple;
}
