// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`, `partial_cmp`

enum PluginAbility {
  authentication,
  scrobbling,
  metadata,
  audioSource,
  ;
}

enum PluginApi {
  webview,
  localstorage,
  timezone,
  ;
}

class PluginConfiguration {
  final String name;
  final String description;
  final String version;
  final String author;
  final String entryPoint;
  final String pluginApiVersion;
  final List<PluginApi> apis;
  final List<PluginAbility> abilities;
  final String? repository;

  const PluginConfiguration({
    required this.name,
    required this.description,
    required this.version,
    required this.author,
    required this.entryPoint,
    required this.pluginApiVersion,
    required this.apis,
    required this.abilities,
    this.repository,
  });

  Future<String> slug() =>
      RustLib.instance.api.crateApiPluginModelsCorePluginConfigurationSlug(
        that: this,
      );

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      version.hashCode ^
      author.hashCode ^
      entryPoint.hashCode ^
      pluginApiVersion.hashCode ^
      apis.hashCode ^
      abilities.hashCode ^
      repository.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginConfiguration &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          version == other.version &&
          author == other.author &&
          entryPoint == other.entryPoint &&
          pluginApiVersion == other.pluginApiVersion &&
          apis == other.apis &&
          abilities == other.abilities &&
          repository == other.repository;
}

class PluginUpdateAvailable {
  final String downloadUrl;
  final String version;
  final String? changelog;

  const PluginUpdateAvailable({
    required this.downloadUrl,
    required this.version,
    this.changelog,
  });

  @override
  int get hashCode =>
      downloadUrl.hashCode ^ version.hashCode ^ changelog.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginUpdateAvailable &&
          runtimeType == other.runtimeType &&
          downloadUrl == other.downloadUrl &&
          version == other.version &&
          changelog == other.changelog;
}

class ScrobbleAlbum {
  final String id;
  final String name;

  const ScrobbleAlbum({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrobbleAlbum &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class ScrobbleArtist {
  final String id;
  final String name;

  const ScrobbleArtist({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrobbleArtist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class ScrobbleDetails {
  final String id;
  final String title;
  final List<ScrobbleArtist> artists;
  final ScrobbleAlbum album;
  final PlatformInt64? timestamp;
  final int? durationMs;
  final String? isrc;

  const ScrobbleDetails({
    required this.id,
    required this.title,
    required this.artists,
    required this.album,
    this.timestamp,
    this.durationMs,
    this.isrc,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      album.hashCode ^
      timestamp.hashCode ^
      durationMs.hashCode ^
      isrc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrobbleDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          album == other.album &&
          timestamp == other.timestamp &&
          durationMs == other.durationMs &&
          isrc == other.isrc;
}
