// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'core.freezed.dart';
part 'core.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`, `partial_cmp`

enum PluginAbility {
  authentication,
  scrobbling,
  metadata,
  audioSource,
  ;
}

enum PluginApi {
  webview,
  localstorage,
  timezone,
  ;
}

@freezed
sealed class PluginConfiguration with _$PluginConfiguration {
  const PluginConfiguration._();
  const factory PluginConfiguration({
    required String name,
    required String description,
    required String version,
    required String author,
    required String entryPoint,
    required String pluginApiVersion,
    required List<PluginApi> apis,
    required List<PluginAbility> abilities,
    String? repository,
  }) = _PluginConfiguration;
  String slug() =>
      RustLib.instance.api.crateApiPluginModelsCorePluginConfigurationSlug(
        that: this,
      );

  factory PluginConfiguration.fromJson(Map<String, dynamic> json) =>
      _$PluginConfigurationFromJson(json);
}

@freezed
sealed class PluginUpdateAvailable with _$PluginUpdateAvailable {
  const factory PluginUpdateAvailable({
    required String downloadUrl,
    required String version,
    String? changelog,
  }) = _PluginUpdateAvailable;

  factory PluginUpdateAvailable.fromJson(Map<String, dynamic> json) =>
      _$PluginUpdateAvailableFromJson(json);
}

@freezed
sealed class ScrobbleAlbum with _$ScrobbleAlbum {
  const factory ScrobbleAlbum({
    required String id,
    required String name,
  }) = _ScrobbleAlbum;

  factory ScrobbleAlbum.fromJson(Map<String, dynamic> json) =>
      _$ScrobbleAlbumFromJson(json);
}

@freezed
sealed class ScrobbleArtist with _$ScrobbleArtist {
  const factory ScrobbleArtist({
    required String id,
    required String name,
  }) = _ScrobbleArtist;

  factory ScrobbleArtist.fromJson(Map<String, dynamic> json) =>
      _$ScrobbleArtistFromJson(json);
}

@freezed
sealed class ScrobbleDetails with _$ScrobbleDetails {
  const factory ScrobbleDetails({
    required String id,
    required String title,
    required List<ScrobbleArtist> artists,
    required ScrobbleAlbum album,
    int? timestamp,
    int? durationMs,
    String? isrc,
  }) = _ScrobbleDetails;

  factory ScrobbleDetails.fromJson(Map<String, dynamic> json) =>
      _$ScrobbleDetailsFromJson(json);
}
