// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'browse.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'playlist.dart';
import 'track.dart';
import 'user.dart';
part 'pagination.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
sealed class SpotubePaginationResponseObject
    with _$SpotubePaginationResponseObject {
  const factory SpotubePaginationResponseObject({
    required int limit,
    int? nextOffset,
    required int total,
    required bool hasMore,
    required List<SpotubePaginationResponseObjectItem> items,
  }) = _SpotubePaginationResponseObject;
}

@freezed
sealed class SpotubePaginationResponseObjectItem
    with _$SpotubePaginationResponseObjectItem {
  const SpotubePaginationResponseObjectItem._();

  const factory SpotubePaginationResponseObjectItem.track(
    SpotubeTrackObject field0,
  ) = SpotubePaginationResponseObjectItem_Track;
  const factory SpotubePaginationResponseObjectItem.playlistFull(
    SpotubeFullPlaylistObject field0,
  ) = SpotubePaginationResponseObjectItem_PlaylistFull;
  const factory SpotubePaginationResponseObjectItem.playlistSimple(
    SpotubeSimplePlaylistObject field0,
  ) = SpotubePaginationResponseObjectItem_PlaylistSimple;
  const factory SpotubePaginationResponseObjectItem.albumSimple(
    SpotubeSimpleAlbumObject field0,
  ) = SpotubePaginationResponseObjectItem_AlbumSimple;
  const factory SpotubePaginationResponseObjectItem.albumFull(
    SpotubeFullAlbumObject field0,
  ) = SpotubePaginationResponseObjectItem_AlbumFull;
  const factory SpotubePaginationResponseObjectItem.artistFull(
    SpotubeFullArtistObject field0,
  ) = SpotubePaginationResponseObjectItem_ArtistFull;
  const factory SpotubePaginationResponseObjectItem.artistSimple(
    SpotubeSimpleArtistObject field0,
  ) = SpotubePaginationResponseObjectItem_ArtistSimple;
  const factory SpotubePaginationResponseObjectItem.browseSection(
    SpotubeBrowseSectionObject field0,
  ) = SpotubePaginationResponseObjectItem_BrowseSection;
}
