// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'user.dart';
part 'playlist.freezed.dart';
part 'playlist.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
sealed class SpotubeFullPlaylistObject with _$SpotubeFullPlaylistObject {
  const factory SpotubeFullPlaylistObject({
    required String typeName,
    required String id,
    required String name,
    required String description,
    required String externalUri,
    required SpotubeUserObject owner,
    required List<SpotubeImageObject> images,
    required List<SpotubeUserObject> collaborators,
    required bool collaborative,
    required bool public,
  }) = _SpotubeFullPlaylistObject;

  factory SpotubeFullPlaylistObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeFullPlaylistObjectFromJson(json);
}

@freezed
sealed class SpotubeSimplePlaylistObject with _$SpotubeSimplePlaylistObject {
  const factory SpotubeSimplePlaylistObject({
    required String typeName,
    required String id,
    required String name,
    required String description,
    required String externalUri,
    required SpotubeUserObject owner,
    required List<SpotubeImageObject> images,
  }) = _SpotubeSimplePlaylistObject;

  factory SpotubeSimplePlaylistObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeSimplePlaylistObjectFromJson(json);
}
