// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'playlist.dart';
import 'track.dart';
import 'user.dart';
part 'search.freezed.dart';
part 'search.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
sealed class SpotubeSearchResponseObject with _$SpotubeSearchResponseObject {
  const factory SpotubeSearchResponseObject({
    required String typeName,
    required List<SpotubeSimpleAlbumObject> albums,
    required List<SpotubeFullArtistObject> artists,
    required List<SpotubeSimplePlaylistObject> playlists,
    required List<SpotubeFullTrackObject> tracks,
  }) = _SpotubeSearchResponseObject;

  factory SpotubeSearchResponseObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeSearchResponseObjectFromJson(json);
}
