// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'track.freezed.dart';
part 'track.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

@freezed
sealed class SpotubeFullTrackObject with _$SpotubeFullTrackObject {
  const factory SpotubeFullTrackObject({
    required String typeName,
    required String id,
    required String name,
    required String externalUri,
    required List<SpotubeSimpleArtistObject> artists,
    required SpotubeSimpleAlbumObject album,
    required int durationMs,
    required String isrc,
    required bool explicit,
  }) = _SpotubeFullTrackObject;

  factory SpotubeFullTrackObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeFullTrackObjectFromJson(json);
}

@freezed
sealed class SpotubeLocalTrackObject with _$SpotubeLocalTrackObject {
  const factory SpotubeLocalTrackObject({
    required String typeName,
    required String id,
    required String name,
    required String externalUri,
    required List<SpotubeSimpleArtistObject> artists,
    required SpotubeSimpleAlbumObject album,
    required int durationMs,
    required String path,
  }) = _SpotubeLocalTrackObject;

  factory SpotubeLocalTrackObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeLocalTrackObjectFromJson(json);
}

@freezed
sealed class SpotubeTrackObject with _$SpotubeTrackObject {
  const SpotubeTrackObject._();

  const factory SpotubeTrackObject.full(
    SpotubeFullTrackObject field0,
  ) = SpotubeTrackObject_Full;
  const factory SpotubeTrackObject.local(
    SpotubeLocalTrackObject field0,
  ) = SpotubeTrackObject_Local;

  factory SpotubeTrackObject.fromJson(Map<String, dynamic> json) =>
      _$SpotubeTrackObjectFromJson(json);
}
